//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Turbo.WebUI.AppCode.Resources.User.LayoutUI", typeof(LayoutUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saytın Administrasiyası reklam bannerlərinin və yerləşdirilmiş elanların məzmununa görə məsuliyyət daşımır..
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ətraflı axtarış.
        /// </summary>
        public static string Advancedsearch {
            get {
                return ResourceManager.GetString("Advancedsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün elanlar.
        /// </summary>
        public static string Allannouncements {
            get {
                return ResourceManager.GetString("Allannouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün markalar.
        /// </summary>
        public static string Allbrands {
            get {
                return ResourceManager.GetString("Allbrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bütün modellər.
        /// </summary>
        public static string Allmodels {
            get {
                return ResourceManager.GetString("Allmodels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barter.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan yerləşdir.
        /// </summary>
        public static string Createannouncement {
            get {
                return ResourceManager.GetString("Createannouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qanun.
        /// </summary>
        public static string Law {
            get {
                return ResourceManager.GetString("Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hər hansı bir məlumatı, materialı və fotoşəkili administrasiyanın yazılı icazəsi olmadan istifadə etmək qeyri-qanuni hesab ediləcək və Azərbaycan Respublikasının Qanunlarına əsasən cəzalandırılacaqdır..
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məxfilik siyasəti.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son elanlar.
        /// </summary>
        public static string Recentannouncements {
            get {
                return ResourceManager.GetString("Recentannouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaydalar.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmişlər.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəstək xidməti.
        /// </summary>
        public static string Supportservice {
            get {
                return ResourceManager.GetString("Supportservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi razılaşması.
        /// </summary>
        public static string Useragreement {
            get {
                return ResourceManager.GetString("Useragreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buraxılış ili.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
