//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivacyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Turbo.WebUI.AppCode.Resources.User.PrivacyResource", typeof(PrivacyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məxfilik siyasəti.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəxsi məlumatların işlənməsinin məqsədləri, o cümlədən, aşağıdakılardır:.
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis İstifadəçilər haqqında növbəti informasiyanı toplayır:.
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisdən istifadə zamanı Administrasiyaya İstifadəçinin daxil etdiyi şəxsi informasiyanı göstərir və ya başqa üsulla açır. Belə informasiya, xüsusi halda (lakin, məhdudlaşdırılmadan), İstifadəçinin adı
        ///            və soyadı, elektron poçt ünvanı və parolu, telefon nömrəsi, İstifadəçinin yerləşdiyi yer, həmçinin ünvanı ola bilər. Əgər İstifadəçi sosial şəbəkənin profili vasitəsilə daxil olursa, Servis həmçinin belə sosial şəbəkənin
        ///            profilində yerləşdirilmiş informasiyanı toplaya bilər. İstifad [rest of string was truncated]&quot;;.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis, həmçinin də Administrasiya, irqi və ya etnik mənşə haqqında məlumatları, siyasi, dini və dünyagörüşü məsləklər, siyasi partiyalara və həmkarlar ittifaqlarına üzvlük, cinayət cəzasına məhkumluqlar,
        ///            həmçinin də sağlamlığa, cinsiyyət həyatına aid olan məlumatları, biometrik və ya genetik məlumatları toplamır və işləmir..
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis və Administrasiya Servisə aidiyyəti olmayan üçüncü şəxslərə İstifadəçilər tərəfindən təqdim edilmiş heç bir şəxsi və ya başqa məlumatları, İstifadəçinin belə icazəni verdiyi hal istisna olmaqla,
        ///            həmçinin də İstifadəçi razılaşması ilə və ya qanunvericiliklə nəzərdə tutulmuş hallarda, vermir..
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi haqqında şəxsi məlumatları silmək üçün  ilə əlaqə saxlamalısınız..
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies, veb-mayaklar, və oxşar texnologiyalar.
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis informasiyanın saxlanılması üçün cookies fayllarından, veb-mayaklardan və başqa oxşar texnologiyalardan istifadə edə bilər. Bu fayllar veb-saytın və onun əlavələrinin istifadəsini yüngülləşdirmək
        ///            məqsədi ilə, Servis xidmətlərinin keyfiyyətinin artırılması məqsədi ilə (həmçinin təhlükəsizlik), həmçinin reklam məqsədi ilə istifadə olunur..
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies-ə və oxşar texnologiyalara icazə olunmamış girişin qarşısını almaq üçün Administrasiya bütün təhlükəsizlik tədbirlərini görür. İstifadəçi analoji təhlükəsizlik tədbirlərini görməyi öhdəsinə götürür.
        ///            Administrasiya zəmanət verir ki, yalnız Administrasiya və/və ya Servis xidmətlərinin səlahiyyətli təchizatçıları cookies məlumatlarına girişə malikdirlər..
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisin xidmətlərinin təchizatçıları Servisin müxtəlif aspektləri ilə kömək edən şirkətlərdir. Administrasiya Servisin uyğun olan xidmətlərinin İstifadəçiyə verilməsi, həmçinin də Servisin bilavasitə
        ///            fəaliyyəti ilə bağlı başqa məqsədlər üçün xidmətlərin bəzi səlahiyyətli təchizatçılarından istifadə edir. Xidmətlərin belə təchizatçıları həmçinin Servisin (kənar cookies) xidmətləri vasitəsilə cookies-i İstifadəçinin qurğusunda
        ///            yerləşdirə bilərlər. Onlar həmçinin başqa informasiyanı, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məxfilik siyasəti.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisin yuxarıda göstərilmiş texnologiyalardan istifadə vasitəsilə toplayıb və saxladığı istənilən informasiyadan İstifadəçinin icazəsi ilə istifadə olunur..
        /// </summary>
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məxfiliyin siyasətinə dəyişikliklərin daxil etməsi.
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasiya Məxfilik Siyasətinə dəyişikliklər edə, silə və ya qaydalarını yeniləyə bilər..
        /// </summary>
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əgər İstifadəçi daxil edilmiş dəyişikliklərlə razı deyilsə, o Servisdən istifadəni dayandırmalıdır. Əgər İstifadəçi Servisdən istifadə etməyə davam edirsə, o razılaşır və bütün dəyişiklikləri və Məxfilik
        ///            siyasətinin yeni redaksiyasını bütövlükdə qəbul edir..
        /// </summary>
        public static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırkı məxfilik Siyasəti turbo.az Servisin İstifadəçi Razılaşmasının ayrılmaz hissəsidir..
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırkı məxfilik Siyasəti İstifadəçinin şəxsi məlumatlarının alması, saxlaması, işlənməsi, istifadəsi, açılması və müdafiəsi qaydasını müəyyən edir..
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçilərin şəxsi məlumat bazası Administrasiyanın ünvanı üzrə yerləşir..
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəxsi məlumatlar Bazasının sərəncamçısı Administrasiyadır – “DİGİTAL CLASSİFİEDS MMC” şirkətidir..
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elanın dərc edilməsi üçün formanı dolduran zaman və ya Servisdə İstifadəçinin qeydiyyatı zamanı, və ya göndərmələrə abunə yazılma zamanı, həmçinin də Servisdən istifadənin başqa hallarında, İstifadəçi
        ///            Administrasiyaya məlumatları və şəxsi məlumatları verir. Məlumatın toplanması həmçinin Servisin İstifadəçilərinin sorğularının keçirilməsi yolu ilə həyata keçirilə bilər. İstifadəçilərin sorğularında iştirak İstifadəçilər
        ///            icazəsi ilə həyata keçirilir..
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi Servisə özü haqqında şəxsi məlumatların və istənilən başqa informasiyanın verilməsi haqqında sərbəst və könüllü qərar qəbul edir, həmçinin də bununla belə şəxsi məlumatların və informasiyanın
        ///            Administrasiya tərəfindən işlənməsinə, işlənməsi üçün onların Administrasiyanın tapşırığı ilə hərəkət edən başqa İstifadəçilərə və/və ya üçüncü şəxslərə ötürülməsinə öz razılığını bildirir..
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəxsi məlumatların işlənməsi istənilən hərəkət və ya hərəkətlərin toplanma, qeydiyyat, yığım, saxlama, uyğunlaşma, dəyişiklik, yeniləmə, istifadə və yayılma kimi məcmusudur (yayılma, reallaşdırma, ötürülmə,
        ///            həmçinin xaricə) və şəxsi məlumatların, həmçinin informasiya (avtomatlaşdırılmış) sistemlərinin istifadəsi ilə məhv edilməsidir..
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
