//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Useragreement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Useragreement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Turbo.WebUI.AppCode.Resources.User.Useragreement", typeof(Useragreement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi razılaşması.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasiya istənilən vaxt birtərəfli qaydada hazırkı Razılaşmanın şərtlərini dəyişdirmək hüququna malikdir..
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçinin hazırkı Razılaşmanın şərtləri ilə və ya ona daxil edilmiş dəyişikliklərlə razılaşmadığı halda o Servisə girişdən imtina etməli, Servisin xidmətlərindən istifadə etməsini dayandırmalıdır..
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bununla Administrasiya İstifadəçilərə Servisin xidmətlərindən istifadə etməklə elanların yerləşdirilməsi və axtarışı üzrə xidmətləri təklif edir..
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayrı xidmətlərin verilməsi xüsusi qaydalarla və/və ya razılaşmalarla tənzimlənə bilər..
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi o haqda müddəanı qəbul edir ki, Servisin bütün materialları və xidmətləri və ya onların istənilən hissəsi reklamla müşayiət oluna bilər. İstifadəçi onunla razıdır ki, Administrasiya hər hansı
        ///            məsuliyyəti daşımır və belə reklamla əlaqədar hər hansı öhdəlikləri yoxdur..
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servisdə qeydiyyat könüllüdür. Servisdə qeydiyyat halında İstifadəçi Servisin əlavə xidmətlərinə daxil olur. Administrasiya İstifadəçidən onun qeydiyyat vaxtı göstərdiyi məlumatların təsdiqlənməsini və
        ///            təsdiqləyici sənədləri istənilən vaxt tələb etmək hüququnu öz ayağında saxlayır..
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi öz parolunu gizli saxlamağı öhdəsinə götürür. İstifadəçi öz elektron ünvanından və paroldan istifadə ilə hərəkətlərə, həmçinin də İstifadəçinin Şəxsi kabinetində yerinə yetirilən hərəkətlərə
        ///            görə məsuliyyət daşıyır..
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasiya İstifadəçilər tərəfindən qeydiyyat və/və ya avtorizasiya zamanı verilən informasiyanın düzgünlüyünün yoxlanması üçün xüsusi texniki qərarlardan istifadə etməkdə haqlıdır..
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasiya zəmanət verə bilməz ki, İstifadəçi həqiqətən təqdim edildiyi kimidir, Servisdə qeydiyyat zamanı İstifadəçi tərəfindən verilmiş informasiya isə doğrudur..
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçiyə bunun üçün Servisdə mümkün olan bütün alətlərdən istifadə edərək mümkün kontragentlərlə ünsiyyət saxlamağa tövsiyə edilir..
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ümumi şərtlər.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasiya öz şəxsi mülahizəsi üzrə İstifadəçinin hazırkı Razılaşmanın şərtlərini pozan xidmətlərinə girişi dayandırmaq hüququnu öz ayağında saxlayır.&lt;/p&gt;.
        /// </summary>
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi təsdiqləyir ki, hazırkı Razılaşmanın bütün bəndləri ilə tanış edilmişdir və onları sözsüz tam həcmdə qəbul edir..
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son yeniləmə tarixi.
        /// </summary>
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Həmin Razılaşma.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Həmin İstifadəçi Razılaşmanın məqsədləri üçün aşağıda göstərilən terminlər və təyinlər aşağıdakı mənada tətbiq olunur:.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Həmin İstifadəçi Razılaşmasında istifadə olunan və &quot;Terminlər və təyinlər&quot; bəndində əksini tapmayan istənilən terminlər və anlayışlar, İstifadəçi Razılaşmasının mətnindən yaranan mənaya müvafiq olaraq izah
        ///            ediləcəkdir. İstifadəçi Razılaşmasında istifadə edilən terminin və ya təyinin izah edilməsi barədə istənilən fikir ayrılıqlarının yaranması halında Administrasiya tərəfindən müəyyən edilən izah etmə tətbiq ediləcəkdir..
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis xidmətlərindən və materiallarından istifadə edilmə qüvvədə olan qanunvericiliyin normaları, həmçinin də hazırkı Razılaşma ilə tənzimlənir..
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırkı Razılaşma ictimai ofertadır..
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis xidmətlərindən istifadə edərək, İstifadəçi hazırkı Razılaşmaya qoşulur və onun Servis xidmətlərindən istifadə üzrə təlimatlarına riayət etmək şərtlərini və öhdəliklərini qəbul edir..
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət adından Servisdən istifadə halında belə şirkət hazırkı Razılaşmanı və onun şərtlərini qəbul edir..
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
